#define _GNU_SOURCE

#include "keymap.h"
#include <linux/input.h>

uint16_t virtual_key(unsigned int code) {
    if (code >= KEY_A && code <= KEY_Z) return (uint16_t)(0x41 + code - KEY_A);
    if (code >= KEY_1 && code <= KEY_9) return (uint16_t)(0x31 + code - KEY_1);
    if (code >= KEY_F1 && code <= KEY_F12) return (uint16_t)(0x70 + code - KEY_F1);
    switch (code) {
        case KEY_0:
            return 0x30;
        case KEY_MINUS:
            return 0xbd;
        case KEY_EQUAL:
            return 0xbb;
        case KEY_LEFTBRACE:
            return 0xdb;
        case KEY_RIGHTBRACE:
            return 0xdd;
        case KEY_BACKSLASH:
            return 0xdc;
        case KEY_SEMICOLON:
            return 0xba;
        case KEY_APOSTROPHE:
            return 0xde;
        case KEY_GRAVE:
            return 0xc0;
        case KEY_COMMA:
            return 0xbc;
        case KEY_DOT:
            return 0xbe;
        case KEY_SLASH:
            return 0xbf;
        case KEY_BACKSPACE:
            return 0x08;
        case KEY_TAB:
            return 0x09;
        case KEY_ENTER:
            return 0x0d;
        case KEY_LEFTCTRL:
            return 0xa2;
        case KEY_LEFTSHIFT:
            return 0xa0;
        case KEY_LEFTALT:
            return 0xa4;
        case KEY_CAPSLOCK:
            return 0x14;
        case KEY_ESC:
            return 0x1b;
        case KEY_SPACE:
            return 0x20;
        case KEY_PAGEUP:
            return 0x21;
        case KEY_PAGEDOWN:
            return 0x22;
        case KEY_END:
            return 0x23;
        case KEY_HOME:
            return 0x24;
        case KEY_LEFT:
            return 0x25;
        case KEY_UP:
            return 0x26;
        case KEY_RIGHT:
            return 0x27;
        case KEY_DOWN:
            return 0x28;
        case KEY_INSERT:
            return 0x2d;
        case KEY_DELETE:
            return 0x2e;
        case KEY_RIGHTCTRL:
            return 0xa3;
        case KEY_RIGHTSHIFT:
            return 0xa1;
        case KEY_RIGHTALT:
            return 0xa5;
        case KEY_LEFTMETA:
            return 0x5b;
        case KEY_RIGHTMETA:
            return 0x5c;
        case KEY_MENU:
            return 0x5d;
        case KEY_KP0:
            return 0x60;
        case KEY_KP1:
            return 0x61;
        case KEY_KP2:
            return 0x62;
        case KEY_KP3:
            return 0x63;
        case KEY_KP4:
            return 0x64;
        case KEY_KP5:
            return 0x65;
        case KEY_KP6:
            return 0x66;
        case KEY_KP7:
            return 0x67;
        case KEY_KP8:
            return 0x68;
        case KEY_KP9:
            return 0x69;
        case KEY_KPASTERISK:
            return 0x6a;
        case KEY_KPPLUS:
            return 0x6b;
        case KEY_KPMINUS:
            return 0x6d;
        case KEY_KPDOT:
            return 0x6e;
        case KEY_KPSLASH:
            return 0x6f;
        case KEY_KPENTER:
            return 0x0d;
        default:
            return 0;
    }
}
