#ifndef PENDESK_PROTOCOL_H
#define PENDESK_PROTOCOL_H

enum {
    MAX_FRAME = 32 * 1024 * 1024,
    STATE_BLOCKED = 1,
    STATE_VIDEO_PAUSED = 2,
    STATE_MOUSE_PAUSED = 4,
    STATE_RECORDING = 8,
    PROTOCOL_VERSION = 9,
    VIDEO_HEADER = 25,
    VIDEO_PAYLOAD = 1150,
    VIDEO_PACKET = VIDEO_HEADER + VIDEO_PAYLOAD,
    VIDEO_ACK_HEADER = 13,
    AUDIO_HEADER = 17
};

#endif
